# Generated by Django 4.2.1 on 2023-06-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_descricao_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
